import csv
import argparse

def calculate_average_scores(score_list_str):
    """Calculates the average of a list of score strings.
       Skips entries that cannot be converted to float (e.g., "N/A").
       Returns None if no valid scores are found to average.
    """
    valid_scores = []
    for s_str in score_list_str:
        try:
            valid_scores.append(float(s_str))
        except ValueError:
            continue # Skip "N/A" or other non-float strings
    
    if not valid_scores:
        return None # If no valid scores to average
    return sum(valid_scores) / len(valid_scores)

def filter_average_similarity(score_csv_path, target_smi_path, output_smi_path, threshold):
    """
    Filters molecules based on the average similarity score across all queries.
    Reads target SMILES from target_smi_path and scores from score_csv_path.
    """
    
    target_smi_lines = []
    try:
        with open(target_smi_path, 'r') as f_smi:
            for line in f_smi:
                smi = line.strip().split(None, 1)[0] # Take first part if line has more
                if smi: # Ensure non-empty SMILES
                    target_smi_lines.append(smi)
        if not target_smi_lines:
            print(f"Error: No SMILES found in target SMILES file '{target_smi_path}'.")
            return
    except FileNotFoundError:
        print(f"Error: Target SMILES file not found: {target_smi_path}")
        return
    except Exception as e:
        print(f"Error reading target SMILES file '{target_smi_path}': {e}")
        return

    score_rows = []
    try:
        with open(score_csv_path, 'r', newline='') as f_csv:
            reader = csv.reader(f_csv)
            header = next(reader) # Read and skip header
            for row in reader:
                score_rows.append(row) # Each row is a list of score strings
        if not score_rows:
            print(f"Error: No data rows found in score CSV file '{score_csv_path}' (after header).")
            return
    except FileNotFoundError:
        print(f"Error: Score CSV file not found: {score_csv_path}")
        return
    except StopIteration: # next(reader) failed, meaning CSV was empty or header-only
        print(f"Error: Score CSV file '{score_csv_path}' is empty or contains only a header.")
        return
    except Exception as e:
        print(f"Error reading score CSV file '{score_csv_path}': {e}")
        return

    num_target_smiles = len(target_smi_lines)
    num_score_rows = len(score_rows)

    if num_target_smiles != num_score_rows:
        print(f"Error: Number of target SMILES ({num_target_smiles} from '{target_smi_path}') "
              f"does not match the number of data rows in score CSV ({num_score_rows} from '{score_csv_path}').")
        print("Ensure that each data row in the score CSV (after the header) corresponds to a SMILES in the target SMILES file, and that their order is identical.")
        return

    smi_passed_threshold = []
    for i in range(num_target_smiles):
        current_smi = target_smi_lines[i]
        current_scores_str_list = score_rows[i] # This is the list of score strings for this SMILES
        
        average_score = calculate_average_scores(current_scores_str_list)
        
        if average_score is not None and average_score > threshold:
            smi_passed_threshold.append(current_smi)
            
    if not smi_passed_threshold:
        print(f"No molecules found in '{target_smi_path}' with average similarity > {threshold} (based on data from '{score_csv_path}').")
    
    try:
        with open(output_smi_path, 'w') as f_out:
            for smi in smi_passed_threshold:
                f_out.write(smi + "\n")
        print(f"Filtered SMILES written to '{output_smi_path}'. Found {len(smi_passed_threshold)} molecules.")
    except Exception as e:
        print(f"Error writing to output SMILES file '{output_smi_path}': {e}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Filters SMILES based on average similarity score. Reads SMILES from one file and scores from another CSV."
    )
    parser.add_argument(
        "-s", "--score_csv",
        required=True,
        help="Path to the input CSV file containing only similarity scores generated by calc_simi.py (no SMILES column, but with a header)."
    )
    parser.add_argument(
        "-i", "--input_smi_file",
        required=True,
        help="Path to the input SMILES file. The order of lines in this file must exactly match the order of score rows in score_csv."
    )
    parser.add_argument(
        "-o", "--output_smi",
        required=True,
        help="Path to the output SMILES file for filtered molecules."
    )
    parser.add_argument(
        "-t", "--threshold",
        type=float,
        required=True,
        help="Average similarity threshold (e.g., 0.5). SMILES with an average score above this will be kept."
    )

    args = parser.parse_args()
    filter_average_similarity(args.score_csv, args.input_smi_file, args.output_smi, args.threshold)